DROP TABLE lembrete CASCADE CONSTRAINTS;

DROP TABLE objeto CASCADE CONSTRAINTS;

DROP TABLE usuario CASCADE CONSTRAINTS;

DROP TABLE usuario_objects CASCADE CONSTRAINTS;

DROP TABLE usuario_user_objects CASCADE CONSTRAINTS;